# Generated by Django 5.0 on 2023-12-21 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_brand_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, null=True),
        ),
    ]
