# Generated by Django 5.0 on 2023-12-26 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0004_alter_transaction_account_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='account_no',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='is_bankrupt',
        ),
    ]
