# Generated by Django 5.0 on 2023-12-18 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicians_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musicians',
            name='phone',
            field=models.IntegerField(),
        ),
    ]
