# Generated by Django 4.2.6 on 2023-12-12 16:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('musician', '0003_remove_musicians_album'),
        ('album', '0002_remove_album_musician'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='musician',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='musician.musicians'),
        ),
    ]
