# Generated by Django 4.2.6 on 2023-12-12 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0002_remove_album_musician'),
        ('musician', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='musicians',
            name='album',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='album.album'),
        ),
    ]
