# Generated by Django 4.2.6 on 2023-12-12 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musician', '0002_musicians_album'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='musicians',
            name='album',
        ),
    ]
