# Generated by Django 4.2.6 on 2023-12-14 03:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AuthorModel',
        ),
    ]
