# Generated by Django 5.0 on 2023-12-17 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_postsmodel_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postsmodel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='posts/uploads/'),
        ),
    ]
